apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-routes
spec:
  tls:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: test-service
          servicePort: 8080
