apiVersion: v1
kind: Service
metadata:
  name: test-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    k8s-app: spring-boot-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
