name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

          
    - name: bash> find external ip
      id: Abcde
      run: |
        snap install kubectl --classic
        echo "External IP: "$(kubectl get services nginx-ingress-controller --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
