name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

          
    - name: bash> find external ip
      id: Abcde
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        ./kubectl version --client
        echo "External IP: "$(kubectl get services nginx-ingress-controller --output jsonpath='{.status.loadBalancer.ingress[0].ip}')
