name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
    
    - name: bash> ls -l
      id: Abc
      run: |
        echo "$(ls -l)"


    - name: Azure Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    
    - name: Build & Push to Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/spring-boot-app:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/spring-boot-app:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/spring-boot-app:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/spring-boot-app

    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: SpringCluster
        resource-group: ResourceGroup
